(()=>{
  const canvas=document.querySelector('#game-canvas'),shell=document.querySelector('#signal-sprint');if(!canvas||!shell)return;
  const ctx=canvas.getContext('2d'),overlay=document.querySelector('#game-overlay'),startButton=document.querySelector('#game-start'),tag=document.querySelector('#game-tag'),title=document.querySelector('#game-title'),copy=document.querySelector('#game-copy'),cleanEl=document.querySelector('#game-clean'),qualityEl=document.querySelector('#game-quality'),timeEl=document.querySelector('#game-time'),bestEl=document.querySelector('#game-best'),feedback=document.querySelector('#game-feedback');
  const C={ink:'#090b0a',paper:'#f4f2ec',muted:'#90938d',acid:'#c7ff45',blue:'#6078ff',red:'#ff6b62'};
  const lessons={NULL:'NULL means a required value is missing. Validate required fields before analysis.',DUP:'DUP means a duplicate row. Deduplicate records so totals are not inflated.',ERR:'ERR means the value failed its format or type validation.'};
  let w=1,h=1,dpr=1,ground=1,state='idle',visible=true,last=0,elapsed=0,clean=0,mistakes=0,speed=250,spawnIn=1.3,collectIn=.6,gridOffset=0,invincible=0,best=0,raf=0,feedbackTimer=0;
  let obstacles=[],collectibles=[],sparks=[];const player={x:90,y:0,vy:0,width:38,height:68,onGround:true};
  try{best=Number(localStorage.getItem('signalSprintBest')||0)}catch(e){}bestEl.textContent=String(best).padStart(4,'0');
  const quality=()=>Math.max(0,100-mistakes*12),remaining=()=>Math.max(0,60-elapsed);
  function resize(){const r=canvas.getBoundingClientRect();w=Math.max(1,r.width);h=Math.max(1,r.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ground=h*.8;player.x=Math.max(70,w*.14);if(state!=='running')player.y=ground-player.height}
  new ResizeObserver(resize).observe(canvas);resize();
  function updateHud(){cleanEl.textContent=`${clean} / 15`;qualityEl.textContent=`${quality()}%`;qualityEl.style.color=quality()>=70?C.acid:C.red;timeEl.textContent=`${Math.ceil(remaining())}s`;bestEl.textContent=String(best).padStart(4,'0')}
  function say(lead,message,bad=false){feedback.innerHTML=`<strong>${lead}</strong> ${message}`;feedback.style.borderColor=bad?C.red:C.acid;feedback.style.opacity='1';feedbackTimer=4}
  function showOverlay(mode){overlay.hidden=false;if(mode==='pause'){tag.textContent='Pipeline paused';title.textContent='Take a breath.';copy.textContent='Your timer and pipeline are frozen. Resume whenever you are ready.';startButton.textContent='Resume pipeline'}else if(mode==='win'){tag.textContent='Mission complete';title.textContent='Dashboard delivered.';copy.textContent=`You delivered 15 verified records at ${quality()}% quality. Clean inputs create trustworthy insights.`;startButton.textContent='Run again'}else if(mode==='fail'){tag.textContent='Mission incomplete';title.textContent=quality()<70?'Quality dropped too far.':'The dashboard is waiting.';copy.textContent=`You delivered ${clean} of 15 records at ${quality()}% quality. Review the data-quality guide and try again.`;startButton.textContent='Retry mission'}else{tag.textContent='Mission briefing';title.textContent='Build a clean pipeline.';copy.textContent='Collect 15 verified records. Jump over NULL, DUP, and ERR blocks—each represents a real data-quality problem.';startButton.textContent='Start mission'}}
  function reset(){elapsed=0;clean=0;mistakes=0;speed=Math.max(230,w*.3);spawnIn=1.4;collectIn=.55;obstacles=[];collectibles=[];sparks=[];invincible=0;player.y=ground-player.height;player.vy=0;player.onGround=true;say('Objective:','Deliver 15 verified rows with at least 70% quality.');updateHud()}
  function start(){reset();state='running';overlay.hidden=true;last=performance.now();canvas.focus()}
  function resume(){state='running';overlay.hidden=true;last=performance.now();say('Resumed:','The pipeline is moving again.')}
  function pause(){if(state!=='running')return;state='paused';showOverlay('pause')}
  function togglePause(){if(state==='running')pause();else if(state==='paused')resume()}
  function finish(won){state=won?'won':'over';const result=Math.round(clean*100+quality()*5+remaining()*10);if(result>best){best=result;try{localStorage.setItem('signalSprintBest',String(best))}catch(e){}}updateHud();showOverlay(won?'win':'fail')}
  function jump(){if(state==='running'&&player.onGround){player.vy=-Math.max(590,h*1.08);player.onGround=false;burst(player.x+12,ground-2,C.acid,8)}}
  startButton.addEventListener('click',()=>state==='paused'?resume():start());canvas.tabIndex=0;canvas.addEventListener('pointerdown',jump);
  addEventListener('keydown',event=>{if(event.code==='Escape'){event.preventDefault();togglePause();return}if(event.code==='Space'||event.code==='ArrowUp'){event.preventDefault();if(state==='idle'||state==='over'||state==='won')start();else jump()}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='running')pause()});new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible){last=performance.now();loop(last)}},{threshold:.02}).observe(shell);
  function roundedRect(x,y,width,height,r){ctx.beginPath();ctx.roundRect(x,y,width,height,r)}
  function spawnObstacle(){const type=['NULL','DUP','ERR'][Math.floor(Math.random()*3)],height=38+Math.random()*34;obstacles.push({x:w+30,y:ground-height,width:type==='NULL'?46:42,height,type,hit:false});spawnIn=Math.max(.78,1.55-elapsed*.009)+Math.random()*.6}
  function spawnCollectible(){const high=Math.random()>.45;collectibles.push({x:w+28,y:high?ground-132-Math.random()*45:ground-68-Math.random()*24,r:9,collected:false,phase:Math.random()*6});collectIn=.72+Math.random()*.95}
  function burst(x,y,color,count=12){for(let i=0;i<count;i++)sparks.push({x,y,vx:(Math.random()-.5)*190,vy:(Math.random()-.72)*180,life:.55,color})}
  function overlaps(a,b){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y}
  function update(dt){
    elapsed+=dt;if(elapsed>=60){finish(false);return}speed=Math.max(230,w*.3)+Math.min(175,elapsed*2.8);gridOffset=(gridOffset+speed*dt*.22)%48;invincible=Math.max(0,invincible-dt);feedbackTimer=Math.max(0,feedbackTimer-dt);if(!feedbackTimer)feedback.style.opacity='.7';
    player.vy+=Math.max(1400,h*2.7)*dt;player.y+=player.vy*dt;if(player.y>=ground-player.height){player.y=ground-player.height;player.vy=0;player.onGround=true}
    spawnIn-=dt;collectIn-=dt;if(spawnIn<=0)spawnObstacle();if(collectIn<=0)spawnCollectible();obstacles.forEach(o=>o.x-=speed*dt);collectibles.forEach(c=>{c.x-=speed*dt;c.phase+=dt*3});sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=260*dt;s.life-=dt});
    const hitbox={x:player.x+8,y:player.y+5,width:player.width-14,height:player.height-7};obstacles.forEach(o=>{if(!o.hit&&invincible<=0&&overlaps(hitbox,o)){o.hit=true;mistakes++;invincible=1.1;burst(player.x+player.width,player.y+player.height*.52,C.red);say(`${o.type}:`,lessons[o.type],true);updateHud()}});
    collectibles.forEach(c=>{const dx=player.x+player.width*.5-c.x,dy=player.y+player.height*.42-c.y;if(!c.collected&&dx*dx+dy*dy<820){c.collected=true;clean++;burst(c.x,c.y,C.acid);say('Verified:','A validated record was added to the dashboard.');updateHud();if(clean>=15)finish(quality()>=70)}});
    obstacles=obstacles.filter(o=>o.x+o.width>-45&&!o.hit);collectibles=collectibles.filter(c=>c.x>-35&&!c.collected);sparks=sparks.filter(s=>s.life>0);updateHud();
  }
  function drawBackground(t){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#101510');g.addColorStop(.62,'#090b0a');g.addColorStop(1,'#060706');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(244,242,236,.055)';ctx.lineWidth=1;for(let x=-gridOffset;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=ground;y>0;y-=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='rgba(96,120,255,.28)';ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<=w;x+=28){const y=h*.35+Math.sin(x*.017+t*.00055)*20+Math.sin(x*.006+t*.00022)*14;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();ctx.strokeStyle='rgba(199,255,69,.6)';ctx.beginPath();ctx.moveTo(0,ground+.5);ctx.lineTo(w,ground+.5);ctx.stroke();ctx.fillStyle='rgba(199,255,69,.035)';ctx.fillRect(0,ground,w,h-ground)}
  function drawRunner(t){const x=player.x,y=player.y,bob=player.onGround&&state==='running'?Math.abs(Math.sin(t*.014))*2:0,phase=t*.018;ctx.save();ctx.translate(x,y-bob);if(invincible>0&&Math.floor(invincible*12)%2===0)ctx.globalAlpha=.3;const hip={x:17,y:44},shoulder={x:18,y:22},swing=state==='running'?Math.sin(phase)*9:0;ctx.strokeStyle='#273029';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(hip.x,hip.y);ctx.lineTo(11+swing*.45,57);ctx.lineTo(7-swing*.32,67);ctx.moveTo(hip.x,hip.y);ctx.lineTo(24-swing*.45,56);ctx.lineTo(31+swing*.32,66);ctx.stroke();ctx.strokeStyle='#313a32';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(shoulder.x,shoulder.y+2);ctx.lineTo(10-swing*.38,35);ctx.lineTo(6-swing*.62,44);ctx.moveTo(shoulder.x+2,shoulder.y+2);ctx.lineTo(28+swing*.38,34);ctx.lineTo(33+swing*.62,42);ctx.stroke();roundedRect(10,18,17,31,7);ctx.fillStyle='#202721';ctx.fill();ctx.fillStyle=C.acid;ctx.fillRect(21,23,2.5,20);ctx.fillStyle='#b97755';ctx.beginPath();ctx.arc(19,11,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111311';ctx.beginPath();ctx.arc(16,7,9,Math.PI,Math.PI*2);ctx.lineTo(26,8);ctx.fill();ctx.fillStyle=C.paper;ctx.beginPath();ctx.arc(24,10,2.8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(25,10,1.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=C.acid;ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(24,10,4.3,0,Math.PI*2);ctx.stroke();ctx.fillStyle=C.paper;ctx.fillRect(1,64,11,4);ctx.fillRect(26,64,12,4);ctx.restore()}
  function drawObstacle(o){ctx.save();ctx.shadowColor=C.red;ctx.shadowBlur=13;roundedRect(o.x,o.y,o.width,o.height,5);ctx.fillStyle='#1b1111';ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,107,98,.85)';ctx.stroke();ctx.fillStyle=C.red;ctx.font='750 9px Inter,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.type,o.x+o.width/2,o.y+o.height/2);ctx.restore()}
  function drawCollectible(c){const pulse=1+Math.sin(c.phase)*.14;ctx.save();ctx.translate(c.x,c.y);ctx.rotate(Math.PI/4);ctx.shadowColor=C.acid;ctx.shadowBlur=18;ctx.fillStyle=C.acid;ctx.fillRect(-c.r*pulse,-c.r*pulse,c.r*2*pulse,c.r*2*pulse);ctx.shadowBlur=0;ctx.fillStyle=C.ink;ctx.fillRect(-2,-2,4,4);ctx.restore()}
  function draw(t){drawBackground(t);collectibles.forEach(drawCollectible);obstacles.forEach(drawObstacle);drawRunner(t);sparks.forEach(s=>{ctx.globalAlpha=Math.max(0,s.life/.55);ctx.fillStyle=s.color;ctx.fillRect(s.x,s.y,3,3);ctx.globalAlpha=1})}
  function loop(now){cancelAnimationFrame(raf);if(!visible)return;const dt=Math.min(.03,(now-last)/1000||0);last=now;if(state==='running')update(dt);draw(now);raf=requestAnimationFrame(loop)}
  reset();showOverlay('intro');loop(performance.now());
})();
